[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
		'@chainlink/=lib/chainlink-brownie-contracts',
    # '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
		'@openzeppelin/=lib/openzeppelin-contracts/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config