[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
remappings = [
		'@openzeppelin/=lib/openzeppelin-contracts/',
		# '@chainlink/=lib/chainlink-brownie-contracts',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
		'@chainlink/contracts/=node_modules/@chainlink/contracts',
]
solc = '0.8.19'

[rpc_endpoints]
ethereumSepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
avalancheFuji = "${AVALANCHE_FUJI_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config